### ISSUE TITLE
Feature: User can Search for Exercises

### ISSUE THREAD

**Issue by kepsteen** [kepsteen/fitlog#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can Search for Exercises and view the results

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can input different search terms such as the name of the exercise or muscles and the app will return a list of cards containing info about the exercises that match the search term

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/kepsteen/front-end-project/assets/118944207/87371410-15b4-4752-b514-15df2192dfbd)
![image](https://github.com/kepsteen/front-end-project/assets/118944207/f52f2789-a9b0-4e65-9ef2-4899f2ea019c)
![image](https://github.com/kepsteen/front-end-project/assets/118944207/822a71d9-e13b-435a-a26a-009a5ccb1143)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Create the responsive navbar
  - [x] style for mobile devices first 
- [x] Create the HTML for the body
  - [x] Add an input input element for the search bar
  - [x] Add the Logo to be displayed when there are no exercises displayed
  - [x] Create a home view and a exercises view
- [x] Create a list of views that contains the different views
- [x] Create a function viewSwap to switch views from home to exercises-view
  - [x] Iterate through the array and conditionally remove or add the hidden class to hide or show views 
- [x] Create an event listener that listens for submission on the form in the search bar with a callback function that does the following:
  - [x] prevent the default action of the form submission
  - [x]  call view swap to swap to exercises-view
  - [x] requests the /api/v2/exercise/search/ endpoint with the language and search parameter
  - [x] Parse the data
  - [x] Creates an array of exercise objects with properties: exercise name, image and description
  - [x] creates a card for each exercise object in the array and display the card on the screen
  - [x] if no exercises are found matching the search term display a message for the user and the logo
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
