### ISSUE TITLE
Feature: User can add exercises to workouts

### ISSUE THREAD

**Issue by kepsteen** [kepsteen/fitlog#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add exercises to created workouts
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click add to workout icon on the exercise card or on the button in the exercise details view and then choose which workouts to add the exercise to.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Add exercise to workout](https://github.com/kepsteen/front-end-project/assets/118944207/255501b6-64d3-4042-a163-7c7d62fe6698)
![Add exercise with modal](https://github.com/kepsteen/front-end-project/assets/118944207/fbc72d2f-b1c4-4c48-b19e-5f1b6ec631e5)
![Add to workout with modal 2](https://github.com/kepsteen/front-end-project/assets/118944207/c708d63c-af06-4d76-be21-9da9d8502624)
![Add to workout -1](https://github.com/kepsteen/front-end-project/assets/118944207/7bcc3ab8-2060-446e-83ec-fd70cdcf50a3)
![Add to workout -2](https://github.com/kepsteen/front-end-project/assets/118944207/1b10cd42-e14a-44ff-b920-a50113db165b)
![Add to workout -3](https://github.com/kepsteen/front-end-project/assets/118944207/fd21a558-66ba-4a95-8b3c-6ce2913a6843)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Add the following HTML elements:
  - [x] Add to workout button in exercise details section
  - [x] Add to workout modal:
    - [x] add to workout form 
- [x] Add an id property to the workout object and a nextWorkoutId property to the fitlogData object
- [x] Refactor the callback function of the new workout form event listener to give each created workout a unique workout id
- [x] Refactor render exercises function to include the pencil icon to each card rendered
- [x] Refactor the event listener on the card list to check if the target is the pencil icon with a callback function that does the following:
  - [x] Render the add to workout form with a list of the created workouts and checkboxes 
    - [x] Each checkbox should have a data-workout-id attribute with the associated id of the workout 
  - [x] show the add to workout modal 
- [x] Add an event listener to the add to workout form to listen for a submit event on the form with a callback function that does the following:
  - [x] Adds the exercise to the selected workout 
  - [x] closes the modal
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
