### ISSUE TITLE
Feature: User can view workouts

### ISSUE THREAD

**Issue by kepsteen** [kepsteen/fitlog#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view workouts and assign exercises to each day of the workout

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view the workouts and drag and drop the exercises from the exercises list into specific days

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![View Workouts](https://github.com/kepsteen/front-end-project/assets/118944207/e267341a-d4e2-41a4-a1b8-02c08ae5995f)
![View Workouts (1)](https://github.com/kepsteen/front-end-project/assets/118944207/4550c7e9-97af-462c-80a9-de8dc8a805ce)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Refactor workout object to make days an array of day objects
  - [ ] each day object will have a key of the day number and a value of an array of the exercises for that day
- [ ]  Create a new section in the HTML with a `data-view="workouts-view"`
- [ ] Create a renderWorkouts function that has 1 parameter workout object that performs the following:
  - [ ] Creates the workout container containing the workout name, the right carat icon and the columns for the workout data 
  - [ ] Creates one column for the exercises to be assigned
    - [ ] Adds each exercise name of the workout.exercises array to to an unordered list in the column with the draggable attribute 
    - [ ] gives each exercise list item a `data-base-id="exercise.baseId"` and a data-workout-id attribute with the value of the workout id to which the exercise belongs
  - [ ] Conditionally renders one column for each day of the workout.days array with title Day 1, Day 2 etc that contains a ul element with a data-num-day attribute with a value of the corresponding day object key.
    - [ ] Render the exercises that are in the exercises array of the day object 
- [ ] Add an event listener to the right carat icon that listens for a click event with a callback function that does the following:
  - [ ] turns the carat 90 degrees
  - [ ] displays the workout data columns
  - [ ] queries a node list of the exercise list items that match the workout-id of the workout displayed
  - [ ] Add an event listener to each list item to listen for a 'dragstart' event with a callback function that does the following:
    - [ ] clears the dataTransfer cache with clearData() method
    - [ ] Use setData method to set the data to be transfered as the exercise list item's data-base-id value
  - [ ]  Query all the ul elements of the day columns for the workout with a matching workoutId
  - [ ] For each ul element create a event listener that listens for a dragover event that prevents the default behavior
  - [ ] For each ul element create an event listener that listens for the 'drop' event with a callback function that does the following: 
    - [ ] prevents the default behavior of the event
    - [ ] gets the data-base-id value of the dragged element with the getData method of the dataTransfer object
    - [ ] queries for the dragged element with the data-base-id
    - [ ] appends the dragged element to the ul element
    - [ ] Searches the fitlogData.workouts array to find the corresponding workout that matches the data-workout-id of the ul element
      - [ ] Remove the corresponding exercise from the workout.exercises and add it to the corresponding exercises array for the day that matches the ul elements data-num-day value
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
