### ISSUE TITLE
Feature: User can Delete Exercises from Workouts

### ISSUE THREAD

**Issue by kepsteen** [kepsteen/fitlog#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove an exercise from a workout
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can hover over an exercise to reveal a red x and the user can click the x to remove the exercise from the workout
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Delete Exercises from workout](https://github.com/kepsteen/front-end-project/assets/118944207/1911103f-db20-442b-979c-26b9d52bce73)
![image](https://github.com/kepsteen/front-end-project/assets/118944207/7503bcb1-464e-4008-b824-05bedf3ed5b9)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Refactor the renderWorkouts and renderAddedExercises functions to append a red xmark to each list element with class of hidden
- [x] Create an event listener on the workout-data-container to listen for a mouseover event with a callback function that does the following:
  - [x] removes the hidden class on the xmark icon that has a settimeout to hide the icon after a short time
- [x] Create an event listener on the workout-data-container to listen for a click event on the xmark icon with a callback function that does the following:
  - [ ] removes the element from the DOM
  - [ ] removes the exercise from the workouts object  
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
