### ISSUE TITLE
Feature: User can view exercise details

### ISSUE THREAD

**Issue by kepsteen** [kepsteen/fitlog#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view the extended details of an exercise including the primary and secondary muscles targeted by the exercise

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the exercises page the user can click into an exercise and see a zoomed in view of all the details of the exercise

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/kepsteen/front-end-project/assets/118944207/dcae430f-53fa-4a9d-bb72-90fa30e8d6a5)
![image](https://github.com/kepsteen/front-end-project/assets/118944207/b27ed7dd-28a7-420f-9949-91f7a4fd92e3)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Add more descriptive alt values to images
- [x] Create a new section with a `data-view="exercise-details"`
- [x] Create the HTML layout and the styling to display the Name, image, primary muscles, secondary muscles, description and equipment required in the exercise details view
  - [x] Add the heart icon and add to workout button for later features
- [x] Refactor the fetchExerciseDetails function to add the equipment data to the exerciseObj
- [x] Refactor the render exercises function to give each card rendered a data-id attribute with a value of baseId
- [x] Refactor the viewSwap function to handle the new view
- [x] Add an event listener on the card list to listen for a click event with a callback function that does the following
  - [x] viewSwap to the exercise-details view
  - [x] Loop through the exerciseObjArr to find the exerciseObj with a baseId that matches the data-id attribute of the target
  - [x] Populates the exercise details view with the data in the exerciseObj
- [x] Add an event listener to the navbar to make the Exercises anchor tag viewSwap to the exercises view
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
