### ISSUE TITLE
Feature: User can favorite Exercises

### ISSUE THREAD

**Issue by kepsteen** [kepsteen/fitlog#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can favorite exercises

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the heart icon and the application will save the exercise object to local storage

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Favorites](https://github.com/kepsteen/front-end-project/assets/118944207/bd33d777-400d-46a7-926e-210d1ba67d9c)
![FavoriteExercise - details -vew](https://github.com/kepsteen/front-end-project/assets/118944207/7897e1a3-b834-4cb3-9d22-372278a78e8e)
![Favorite Exercise](https://github.com/kepsteen/front-end-project/assets/118944207/f8ed129e-56df-4858-a406-0c504b816d37)
![Favorite exercise-card-view](https://github.com/kepsteen/front-end-project/assets/118944207/ab659567-043a-4f9c-a88c-53410de183bf)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] refactor render Exercises to omit description in cards
- [x] Add favorited property of type boolean to Exercise interface
- [x] Refactor fetchExerciseDetails Function to do the following:
  - [x] assign default value of favorited property of exerciseObj to false
  - [x] conditionally check by baseId if the exerObj to be returned exists in data.favorites and reassign favorited property accordingly
- [x] Create a fitlogData object that has one property favorites that will contain an array of the users favorite exercise objects
- [x] Refactor the render exercises function to do the following:
   - [x] to create a heart icon in the bottom corner of the card
   - [x] conditionally check if the exercise object's favorited property is true/false and render a solid/regular heart icon accordingly
- [x] Create a function called findExerciseByBaseId which takes the baseId of the exercise as an argument and returns the associated exercise Object
- [x] Refactor the populateExerciseDetails function to give the section a data-base-id attribute with a value that matches the baseId of the exercise object populated
- [x] Create a function handleFavoriteClick which takes two arguments exerciseObj and targetIcon that does the following:
  - [x] conditionally checks the status of the heart icon and updates it to reflect if the exerciseObj has been favorited or unfavorited
  - [x] Adds or removes the exerciseObj from the favorites property of the fitlogData Object accordingly
- [x] Add an event listener on the document to listen for a click event on a heart icon with a callback function that does the following:
  - [x]  Conditionally checks if the event target from a card or the details section
  - [x] Get the value of the data-base-id attribute of the card or the details section
  - [x] call the findExerciseByBaseId function and pass the baseId value as an arugment and assign the result to a variable named exercise
  - [x] Call the function handleFavoriteClick and pass the exercise variable as an argument
- [x]  Add an event listener on the window to listen for a before unload event with a callback function that does the following:
  - [x] stringifys the data object
  - [x] Uses the set item method of the localStorage object to save the stringified data to local storage
- [x]  Add an event listener to listen for the Dom content loaded event on the document object with a callback function that does the following:
  - [x] Uses the get item method of the localStorage object to retrieve the json data from local storage
  - [x] if there is data in local storage parse it and reassign the parsed data to the global data object
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
