### ISSUE TITLE
Feature: User can view view favorite exercises

### ISSUE THREAD

**Issue by kepsteen** [kepsteen/fitlog#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of their favorite exercises

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click the favorites link in the navbar and redirect to the favorites page and view a list of their favorite exercises

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![View Favorites (3)](https://github.com/kepsteen/front-end-project/assets/118944207/13c4f375-686c-4db9-b858-4a7fe19b045a)
![Favorites (1)](https://github.com/kepsteen/front-end-project/assets/118944207/2129f99e-10a1-4693-873f-c34fc001f555)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Create a new section element in the HTML with `data-view="favorites-view"`
  - [x] create a container with a class of card-list
- [x] Add favorite links to header
- [x] Refactor header event listener to view swap to favorites if favorites link clicked
- [x] Add event listener to document to listen for DOM content loaded with a callback function that does the following
  - [x] Render the favorite exercises in the favorites-view
- [x] Refactor handleFavoriteClick to add/ remove exercises from favorites-view
  - [x] Make sure favorited status updates accordingly on both favorites-view and exercises-view
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
