### ISSUE TITLE
Feature: User can create a workout plan

### ISSUE THREAD

**Issue by kepsteen** [kepsteen/fitlog#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a new workout plan

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can redirect to the the create page and select from several options to create a custom workout plan

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Create new (2)](https://github.com/kepsteen/front-end-project/assets/118944207/b326352e-9255-4555-9b39-c9d606155098)
![Create new (3)](https://github.com/kepsteen/front-end-project/assets/118944207/bb3d2b06-4437-4437-8f32-226d67e58cd7)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Give the fitlogData object a property workouts that will contain an array of workout objects
- [x] Create a new section element in HTML with  `data-view="new-workout"`
  - [x] Add form element with an input for the name of the workout, a select element for the number of days per week and a submit button
- [x] Add the links to the navbar and hamburger menu
- [x] Style the page and the form to be consist with the rest of the application
- [x] Add an event listener to the form that listens for the submit event with a callback function which adds the workout object to the workout array of the workouts property of the fitlogData object 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
